name: mock_plant_care_app
description: "A modern plant care assistant."
publish_to: "none"

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  awesome_notifications: ^0.11.0
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  smooth_page_indicator: ^2.0.1
  lottie: ^3.3.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.1.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# 1. Launcher Icons Configuration (Root Level)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/plant_icon.png"
  adaptive_icon_background: "#008080"
  adaptive_icon_foreground: "assets/images/plant_image.png"

# 2. Native Splash Configuration (Root Level - Moved out of the flutter block)
flutter_native_splash:
  color: "#F2F7F4"
  image: assets/images/splash.png
  ios_content_mode: scaleAspectFill
  android_12:
    image: assets/icons/plant_icon.png
    color: "#F2F7F4"
    icon_background_color: "#F2F7F4"
    image_dark: assets/icons/plant_icon.png
    color_dark: "#0B1A16"
    icon_background_color_dark: "#0B1A16"
  fullscreen: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: tishk
      fonts:
        - asset: assets/fonts/tishk.ttf
    - family: bahij
      fonts:
        - asset: assets/fonts/bahij.ttf
